### ISSUE TITLE
NotInTransactionException in golr loader

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/golr-loader#30]
Stack trace:
```
May 05, 2017 1:09:48 AM org.monarch.golr.GolrWorker call
INFO: Deleting JSON pathway-phenotype.yaml.json
May 05, 2017 1:09:51 AM org.monarch.golr.GolrWorker call
INFO: pathway-phenotype.yaml.json done
May 05, 2017 1:09:51 AM org.monarch.golr.GolrWorker call
INFO: Posting JSON gene-phenotype.yaml.json to http://localhost:8983/solr/golr
May 05, 2017 1:47:40 AM org.monarch.golr.GolrWorker call
INFO: {"responseHeader":{"status":0,"QTime":2269002}}

**May 05, 2017 1:47:40 AM org.monarch.golr.GolrWorker call
INFO: Deleting JSON gene-phenotype.yaml.json
May 05, 2017 1:47:42 AM org.monarch.golr.GolrWorker call
INFO: gene-phenotype.yaml.json done**
May 05, 2017 1:47:42 AM org.monarch.golr.GolrWorker call
INFO: Posting JSON literature-variant.yaml.json to http://localhost:8983/solr/golr
May 05, 2017 3:52:05 AM org.monarch.golr.GolrWorker call
INFO: {"responseHeader":{"status":0,"QTime":7462131}}

May 05, 2017 3:52:05 AM org.monarch.golr.GolrWorker call
INFO: Deleting JSON literature-variant.yaml.json
May 05, 2017 3:52:07 AM org.monarch.golr.GolrWorker call
INFO: literature-variant.yaml.json done
Exception in thread "Golr processor - gene-phenotype.yaml.json" java.util.concurrent.ExecutionException: org.neo4j.graphdb.NotInTransactionException: The statement has been closed.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.monarch.golr.Pipeline.main(Pipeline.java:190)
Caused by: org.neo4j.graphdb.NotInTransactionException: The statement has been closed.
	at org.neo4j.kernel.impl.api.KernelStatement.assertOpen(KernelStatement.java:153)
	at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:346)
	at org.neo4j.kernel.impl.core.NodeProxy$1.iterator(NodeProxy.java:189)
	at org.neo4j.kernel.impl.core.NodeProxy$1.iterator(NodeProxy.java:181)
	at io.scigraph.internal.EvidenceAspect.invoke(EvidenceAspect.java:80)
	at org.monarch.golr.EvidenceProcessor.addAssociations(EvidenceProcessor.java:68)
	at org.monarch.golr.GolrLoader.serializeGolrQuery(GolrLoader.java:433)
	at org.monarch.golr.GolrLoader.process(GolrLoader.java:337)
	at org.monarch.golr.GolrWorker.call(GolrWorker.java:53)
	at org.monarch.golr.GolrWorker.call(GolrWorker.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kshefchek** [comment]
Note I can't replicate this when running https://github.com/monarch-initiative/solr-docker-monarch-golr/ locally with a test graph - https://data.monarchinitiative.org/dev/test-graph/

**Comment by kshefchek** [comment]
Closing as I can no longer duplicate, this may have been resolved with the latest PR.
